#ifndef CONSTANT
#define CONSTANT

#define SCALE 27
#define WINDOW_WIDTH 64 * SCALE
#define WINDOW_HEIGHT 32 * SCALE
#define BASE_ADDRESS 0x200
#define INSTRUCTION_SIZE 2
#define STACK_SIZE 128
#define TARGET_FREQUENCY 100

#endif